obj-y 			+= ilitek_main.o
obj-y                   += ilitek_platform_init.o
obj-y                   += ilitek_update.o
obj-y                   += ilitek_tool.o
obj-y                   += ilitek_protocol.o
obj-y                   += ilitek_mp.o

